### ISSUE TITLE
Error: undeclared identifier: 'newContext'

### ISSUE THREAD

**Issue by theSherwood** [treeform/pixie#208]
I'm brand new to Nim, so I'm doubtless doing something simple incorrectly. When I try to run the examples like so

```
nim c -r realtime_sdl.nim
```

I get

```
Error: undeclared identifier: 'newContext'
```

Nim version:

```
Nim Compiler Version 1.4.4 [MacOSX: amd64]
```

**Comment by zetashift** [comment]
So I just ran the example and it worked fine for me

![image](https://user-images.githubusercontent.com/1857826/119579104-07f71000-bdbe-11eb-8f42-91327b28994e.png)

These were the steps to reproduce:
1. `git clone https://github.com/treeform/pixie.git` && `cd pixie` to enter the pixie folder
2. `nimble install -y` to install the correct pixie version
3. `nimble install sdl2@#head` to install the correct sdl2 version
4. `cd examples` and then `nim c -r realtime_sdl.nim`

To always download the latest (and most likely "correct" version) of Pixie instead of cloning manually you can also `nimble install pixie@#head`

**Comment by theSherwood** [comment]
I tried those steps and ended up with a different error:

<img width="834" alt="CleanShot 2021-05-25 at 18 36 51@2x" src="https://user-images.githubusercontent.com/43248857/119585638-4eca1300-bd88-11eb-8c52-ca2c1339d517.png">

**Comment by zetashift** [comment]
The output says you have a successful compilation, you just need to install the SDL2 libraries for your system. Are you on Mac? If so follow: https://github.com/nim-lang/sdl2#macos-with-homebrew

**Comment by theSherwood** [comment]
Oh, amazing! Thank you, @zetashift! Worked a charm

**Comment by treeform** [comment]
Its soo cool seeing other people solve each others problems. Its great!
